# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/dmat/projects/http

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/dmat/projects/http

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/dmat/projects/http/CMakeFiles /home/dmat/projects/http/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/dmat/projects/http/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named test_lhttpd

# Build rule for target.
test_lhttpd: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_lhttpd
.PHONY : test_lhttpd

# fast build rule for target.
test_lhttpd/fast:
	$(MAKE) -f CMakeFiles/test_lhttpd.dir/build.make CMakeFiles/test_lhttpd.dir/build
.PHONY : test_lhttpd/fast

#=============================================================================
# Target rules for targets named httpd

# Build rule for target.
httpd: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 httpd
.PHONY : httpd

# fast build rule for target.
httpd/fast:
	$(MAKE) -f CMakeFiles/httpd.dir/build.make CMakeFiles/httpd.dir/build
.PHONY : httpd/fast

#=============================================================================
# Target rules for targets named lhttpd

# Build rule for target.
lhttpd: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 lhttpd
.PHONY : lhttpd

# fast build rule for target.
lhttpd/fast:
	$(MAKE) -f CMakeFiles/lhttpd.dir/build.make CMakeFiles/lhttpd.dir/build
.PHONY : lhttpd/fast

http.o: http.c.o

.PHONY : http.o

# target to build an object file
http.c.o:
	$(MAKE) -f CMakeFiles/httpd.dir/build.make CMakeFiles/httpd.dir/http.c.o
.PHONY : http.c.o

http.i: http.c.i

.PHONY : http.i

# target to preprocess a source file
http.c.i:
	$(MAKE) -f CMakeFiles/httpd.dir/build.make CMakeFiles/httpd.dir/http.c.i
.PHONY : http.c.i

http.s: http.c.s

.PHONY : http.s

# target to generate assembly for a file
http.c.s:
	$(MAKE) -f CMakeFiles/httpd.dir/build.make CMakeFiles/httpd.dir/http.c.s
.PHONY : http.c.s

jobs_queue.o: jobs_queue.c.o

.PHONY : jobs_queue.o

# target to build an object file
jobs_queue.c.o:
	$(MAKE) -f CMakeFiles/httpd.dir/build.make CMakeFiles/httpd.dir/jobs_queue.c.o
.PHONY : jobs_queue.c.o

jobs_queue.i: jobs_queue.c.i

.PHONY : jobs_queue.i

# target to preprocess a source file
jobs_queue.c.i:
	$(MAKE) -f CMakeFiles/httpd.dir/build.make CMakeFiles/httpd.dir/jobs_queue.c.i
.PHONY : jobs_queue.c.i

jobs_queue.s: jobs_queue.c.s

.PHONY : jobs_queue.s

# target to generate assembly for a file
jobs_queue.c.s:
	$(MAKE) -f CMakeFiles/httpd.dir/build.make CMakeFiles/httpd.dir/jobs_queue.c.s
.PHONY : jobs_queue.c.s

main.o: main.c.o

.PHONY : main.o

# target to build an object file
main.c.o:
	$(MAKE) -f CMakeFiles/lhttpd.dir/build.make CMakeFiles/lhttpd.dir/main.c.o
.PHONY : main.c.o

main.i: main.c.i

.PHONY : main.i

# target to preprocess a source file
main.c.i:
	$(MAKE) -f CMakeFiles/lhttpd.dir/build.make CMakeFiles/lhttpd.dir/main.c.i
.PHONY : main.c.i

main.s: main.c.s

.PHONY : main.s

# target to generate assembly for a file
main.c.s:
	$(MAKE) -f CMakeFiles/lhttpd.dir/build.make CMakeFiles/lhttpd.dir/main.c.s
.PHONY : main.c.s

test.o: test.c.o

.PHONY : test.o

# target to build an object file
test.c.o:
	$(MAKE) -f CMakeFiles/test_lhttpd.dir/build.make CMakeFiles/test_lhttpd.dir/test.c.o
.PHONY : test.c.o

test.i: test.c.i

.PHONY : test.i

# target to preprocess a source file
test.c.i:
	$(MAKE) -f CMakeFiles/test_lhttpd.dir/build.make CMakeFiles/test_lhttpd.dir/test.c.i
.PHONY : test.c.i

test.s: test.c.s

.PHONY : test.s

# target to generate assembly for a file
test.c.s:
	$(MAKE) -f CMakeFiles/test_lhttpd.dir/build.make CMakeFiles/test_lhttpd.dir/test.c.s
.PHONY : test.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... test_lhttpd"
	@echo "... httpd"
	@echo "... rebuild_cache"
	@echo "... lhttpd"
	@echo "... http.o"
	@echo "... http.i"
	@echo "... http.s"
	@echo "... jobs_queue.o"
	@echo "... jobs_queue.i"
	@echo "... jobs_queue.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... test.o"
	@echo "... test.i"
	@echo "... test.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

